apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev-deployment
  namespace: dev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-service
        imagePullPolicy: Always
        image: accountid.dkr.ecr.us-west-2.amazonaws.com/app-develop:{{GIT_SHA}}
        resources:
            limits:
              memory: 128Mi
              cpu: "500m"
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: dev
        envFrom:
          - secretRef:
              name: app-doppler-token
      imagePullSecrets:
        - name: regcred

